config/routes.rb
Rails.application.routes.draw do
  get 'shopping/new' => 'shopping#new', as: 'shopping_new'

  post 'shopping/create' => 'shopping#create', as: 'shopping_create'

  get 'shopping/edit/:id' => 'shopping#edit', as: 'shopping_edit'

  patch 'shopping/update/:id' => 'shopping#update', as: 'shopping_update'

  delete 'shopping/destroy/:id' => 'shopping#destroy', as: 'shopping_destroy'

  get 'shopping/show/:id' => 'shopping#show', as: 'shopping_show'

  get 'shopping/index' => 'shopping#index', as: 'shopping_index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord
	validates :name, presence: {message: 'Preencha o nome'}
end

app/models/store.rb
class Store < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shopping_controller.rb
class ShoppingController < ApplicationController
  def new
    @shop = Shop.new
  end

  def create
    shop = Shop.new(permit)
    if shop.save
      @msg = 'salvo com sucesso'
    else
      @msg = shop.errors.messages 
    end
  end

  def edit
    @shop = Shop.find_by(id: params['id'])
  end

  def update
    shop = Shop.find_by(id: params['id'])
    if shop.update_attributes(permit)
      @msg = 'salvo com sucesso'
    else
      @msg = shop.errors.messages
    end 
  end

  def destroy
    @shop = Shop.find_by(id: params['id']) 
    if shop.destroy
      @msg = 'excluido com sucesso'
    else
      @msg = shop.errors.messages
    end 
  end

  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find_by(id: params['id'])    
  end

private

  def permit 
    params['shop'].permit(:name, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shopping_helper.rb
module ShoppingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shopping/create.html.erb
<h1><%=@msg%></h1>

app/views/shopping/destroy.html.erb
<%= @msg %>

app/views/shopping/edit.html.erb
<h1>Alterar Shopping </h1>

<%= form_for @shop, url:shopping_update_path do |f| %>
	<%= f.label :name, 'Nome'%>
	<%= f.text_field :name%>
	<%= f.label :address, 'Endereço'%>
	<%= f.text_field :address%>
	<%= f.submit 'Alterar'%>
<% end %>

app/views/shopping/index.html.erb
Todos os Shoppings
<table border='5px' style="width: 50%">
	
	<tr>
		<td>Nome</td>
		<td>Alterar</td>
		<td>Remover</td>
	</tr>
<%@shops.each do |shop|%>
	<tr>
		<td><%=link_to shop.name, shopping_show_path(shop.id) %></td>
		<td><%=link_to 'Alterar', shopping_edit_path(shop.id) %></td>
		<td><%= link_to 'remover', shopping_destroy_path(shop.id), :method => 'delete'%> </td>
	</tr>
<% end %>
</table>

app/views/shopping/new.html.erb
<h1>Cadastrar Shopping </h1>

<%= form_for @shop, url:shopping_create_path do |f| %>
	<%= f.label :name, 'Nome'%>
	<%= f.text_field :name%>
	<%= f.label :address, 'Endereço'%>
	<%= f.text_field :address%>
	<%= f.submit 'Enviar'%>
<% end %>

app/views/shopping/show.html.erb
Amostra um<br><br>

Nome: <%= @shop.name %><br><br>

Endereço: <%= @shop.name %><br><br>

<%= link_to 'Voltar', shopping_index_path %>

app/views/shopping/update.html.erb
<%= @msg %><br><br>